name: Export discussions

on:
  discussion:
  discussion_comment:
  workflow_dispatch:
    inputs:
      number:
        description: Discussion number
        required: true

concurrency:
  group: main

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm ci
      - run: node index.js
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCUSSION_NUMBER: ${{ github.event.inputs.number || github.event.discussion.number }}

      - name: Prepare deployment
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/github
          cat >>~/.ssh/config <<EOL
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/github
            User git
          EOL
          chmod 700 ~/.ssh
          chmod -R 600 ~/.ssh/*
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - run: |
          git add discussions
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -q -m "export: ${{ github.event.inputs.number || github.event.discussion.number }}"
          git push origin main
